# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ground',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('cid', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='slot',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('endtime', models.DateTimeField(blank=True)),
                ('no', models.IntegerField(blank=True)),
                ('max', models.IntegerField(blank=True)),
                ('min', models.IntegerField(blank=True)),
                ('sport', models.CharField(blank=True, max_length=20)),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.ground')),
            ],
        ),
    ]
