# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ground',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('cid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='slots',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('gid', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('no', models.IntegerField()),
                ('max', models.IntegerField()),
                ('min', models.IntegerField()),
                ('sport', models.CharField(max_length=20)),
            ],
        ),
    ]
