# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20180310_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='sid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
