# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20180311_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=200, max_digits=5),
        ),
    ]
